name: Windows Cloud PC (Ngrok RDP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: User yaratish va RDP sozlash
      shell: powershell
      run: |
        secedit /export /cfg cfg.ini
        (Get-Content cfg.ini) -replace 'PasswordComplexity = 1', 'PasswordComplexity = 0' | Set-Content cfg.ini
        secedit /configure /db $env:windir\security\new.sdb /cfg cfg.ini /areas SECURITYPOLICY
        net user Sanjar "${{ secrets.PC_PASSWORD }}" /add
        net localgroup Administrators Sanjar /add
        
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

    - name: Ngrok yuklash va TCP 3389 portni ochish
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://bin.equinox.io/c/b4pCviHvc4/ngrok-v3-stable-windows-amd64.zip" -OutFile "ngrok.zip"
        Expand-Archive -Path "ngrok.zip" -DestinationPath "."
        
        .\ngrok.exe config add-authtoken ${{ secrets.NGROK_TOKEN }}
        Start-Process -FilePath ".\ngrok.exe" -ArgumentList "tcp 3389" -RedirectStandardOutput "ngrok.log"
        
        Start-Sleep -Seconds 7
        
        # Ngrok API'dan ochiq IP va portni olish
        $response = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
        $address = $response.tunnels[0].public_url -replace 'tcp://', ''
        
        Write-Host "==========================================" -ForegroundColor Green
        Write-Host "WINDOWS APP UCHUN IP MANZIL: $address" -ForegroundColor Yellow
        Write-Host "==========================================" -ForegroundColor Green

    - name: Cloud PC-ni ochiq tutish (6 soat)
      shell: powershell
      run: |
        Start-Sleep -Seconds 21600
