name: Windows Cloud PC (Pinggy RDP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: User yaratish va RDP sozlash
      shell: powershell
      run: |
        secedit /export /cfg cfg.ini
        (Get-Content cfg.ini) -replace 'PasswordComplexity = 1', 'PasswordComplexity = 0' | Set-Content cfg.ini
        secedit /configure /db $env:windir\security\new.sdb /cfg cfg.ini /areas SECURITYPOLICY
        net user Sanjar "${{ secrets.PC_PASSWORD }}" /add
        net localgroup Administrators Sanjar /add
        
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

    - name: Pinggy TCP Tunnel yoqish
      shell: powershell
      run: |
        # SSH orqali ulanib, javobni pinggy.log fayliga yozamiz
        Start-Process ssh -ArgumentList "-t -t -o StrictHostKeyChecking=no -p 443 -R0:localhost:3389 tcp@a.pinggy.io" -RedirectStandardOutput "pinggy.log" -RedirectStandardError "pinggy_err.log"
        
        Start-Sleep -Seconds 12
        
        # Log fayldan IP va Portni o'qiymiz
        if (Test-Path pinggy.log) {
            Get-Content pinggy.log
        }
        if (Test-Path pinggy_err.log) {
            Get-Content pinggy_err.log
        }

    - name: Cloud PC-ni ochiq tutish (6 soat)
      shell: powershell
      run: |
        Start-Sleep -Seconds 21600
