name: Windows Cloud PC (Playit RDP)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: User yaratish va RDP sozlash
      shell: powershell
      run: |
        secedit /export /cfg cfg.ini
        (Get-Content cfg.ini) -replace 'PasswordComplexity = 1', 'PasswordComplexity = 0' | Set-Content cfg.ini
        secedit /configure /db $env:windir\security\new.sdb /cfg cfg.ini /areas SECURITYPOLICY
        net user Sanjar "${{ secrets.PC_PASSWORD }}" /add
        net localgroup Administrators Sanjar /add
        
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 0
        Set-NetFirewallProfile -Profile Domain,Public,Private -Enabled False

    - name: Playit.gg yuklash va TCP tunnel yoqish
      shell: powershell
      run: |
        Invoke-WebRequest -Uri "https://github.com/playit-cloud/playit-agent/releases/download/v0.15.26/playit-windows-x86_64.exe" -OutFile "playit.exe"
        Start-Process -FilePath ".\playit.exe" -ArgumentList "--claim" -RedirectStandardOutput "playit.log"
        
        Start-Sleep -Seconds 8
        
        Write-Host "==========================================" -ForegroundColor Green
        Get-Content playit.log | Select-String "https://playit.gg/claim/"
        Write-Host "==========================================" -ForegroundColor Green

    - name: Cloud PC-ni ochiq tutish (6 soat)
      shell: powershell
      run: |
        Start-Sleep -Seconds 21600
