name: Windows Cloud PC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: User yaratish va Remote Desktop yoqish
      shell: powershell
      run: |
        secedit /export /cfg cfg.ini
        (Get-Content cfg.ini) -replace 'PasswordComplexity = 1', 'PasswordComplexity = 0' | Set-Content cfg.ini
        secedit /configure /db $env:windir\security\new.sdb /cfg cfg.ini /areas SECURITYPOLICY
        net user Sanjar "${{ secrets.PC_PASSWORD }}" /add
        net localgroup Administrators Sanjar /add
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Ngrok o'rnatish va Manzil chiqarish
      shell: powershell
      run: |
        choco install ngrok -y
        ngrok config add-authtoken ${{ secrets.NGROK_AUTHTOKEN }}
        
        # Ngrok-ni ishga tushiramiz
        Start-Process -FilePath "ngrok" -ArgumentList "tcp 3389"
        Start-Sleep -Seconds 10
        
        # API orqali manzilni olib, logga yozamiz
        $res = Invoke-RestMethod -Uri "http://127.0.0.1:4040/api/tunnels"
        $addr = $res.tunnels[0].public_url
        Write-Host "==========================================" -ForegroundColor Green
        Write-Host "ULANISH MANZILI: $addr" -ForegroundColor Yellow
        Write-Host "==========================================" -ForegroundColor Green

    - name: Cloud PC-ni ochiq tutish (6 soat)
      shell: powershell
      run: |
        Start-Sleep -Seconds 21600
